export const robots = [
	{id:1,
	 name: 'Hsin',
	 username: 'hhsin',
	 email:'hsin@gmail.com',
	},
	{id:2,
	 name: 'Bob',
	 username: 'bbsin',
	 email:'bbin@gmail.com',
	},
	{id:3,
	 name: 'Ken',
	 username: 'ksin',
	 email:'kkn@gmail.com',
	},
	{id:4,
	 name: 'John',
	 username: 'jsin',
	 email:'jjn@gmail.com',
	},
	{id:5,
	 name: 'Tim',
	 username: 'tsin',
	 email:'timjn@gmail.com',
	},
	{id:6,
	 name: 'Kyle',
	 username: 'kylehsu',
	 email:'kyle@gmail.com',
	},
	{id:7,
	 name: 'Jess',
	 username: 'jessica',
	 email:'jess@gmail.com',
	},
]

